// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// is_2k2_neigh
bool is_2k2_neigh(NumericVector n1, NumericVector n2, int v1, int v2);
RcppExport SEXP _nested_comms_is_2k2_neigh(SEXP n1SEXP, SEXP n2SEXP, SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< int >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(is_2k2_neigh(n1, n2, v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// is_2k2_neigh_treshold
bool is_2k2_neigh_treshold(NumericVector n1, NumericVector n2, int v1, int v2, float treshold);
RcppExport SEXP _nested_comms_is_2k2_neigh_treshold(SEXP n1SEXP, SEXP n2SEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP tresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< int >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< float >::type treshold(tresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(is_2k2_neigh_treshold(n1, n2, v1, v2, treshold));
    return rcpp_result_gen;
END_RCPP
}
// is_2k2_neigh_value
float is_2k2_neigh_value(NumericVector n1, NumericVector n2, int v1, int v2);
RcppExport SEXP _nested_comms_is_2k2_neigh_value(SEXP n1SEXP, SEXP n2SEXP, SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< int >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(is_2k2_neigh_value(n1, n2, v1, v2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nested_comms_is_2k2_neigh", (DL_FUNC) &_nested_comms_is_2k2_neigh, 4},
    {"_nested_comms_is_2k2_neigh_treshold", (DL_FUNC) &_nested_comms_is_2k2_neigh_treshold, 5},
    {"_nested_comms_is_2k2_neigh_value", (DL_FUNC) &_nested_comms_is_2k2_neigh_value, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_nested_comms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
